### ISSUE TITLE
Change logo from colored to inverse on press "light/Dark"

### ISSUE THREAD

**Issue by fhilipk** [fhilipk/Cardano-AIM#1]
Cardano_Aim_-_White.png](https://github.com/fhilipk/Cardano-AIM/tree/site-update/images/logo/Cardano_Aim_-_White.png

**Comment by jbmattos** [comment]
adjusted on 45bcc7497d25f18b6997fa328c7c8efcecfc72e6 :
the Cardano_Aim_-_White.png was edited to adjust to the colored logo size proportions.
